### ISSUE TITLE
ufw and docker

### ISSUE THREAD

**Issue by pmmaga** [RocketChat/docs-old#1053]
Not completely sure on how to rewrite it, hence an issue instead of a PR. The issue is that by default (unless disabled via the daemon configuration), docker will manipulate `iptables` directly while completely ignoring your `ufw` rules. Currently, on the docs about installing RC on Docker (docs/installation/docker-containers/README.md) mention the configuration of ufw as means to secure your installation but that will most likely not be enough. I'd recommend either adding a very large warning about this or just scrap the section about ufw so people aren't convinced that it will be enough.

**Comment by dudanogueira** [comment]
Hi!

Since this issue was opened we have totally revamped our deployment docs:
https://docs.rocket.chat/quick-start/installing-and-updating

That, coupled with the [reverse proxy doc ](https://docs.rocket.chat/quick-start/environment-configuration/configuring-ssl-reverse-proxy) give admins a nice path on how to properly deploy Rocket.Chat.

I will close this issue for now, but please, feel free to open a new one if you find any space for improvements here.

Thanks!
