### ISSUE TITLE
service error

### ISSUE THREAD

**Issue by paqxyz** [RocketChat/docs-old#1272]

**Comment by paqxyz** [comment]
server.js:199 System ➔ error

**Comment by Rodriq** [comment]
Please @paqxyz can you describe your issue more?
  Maybe tell us what is happening and what you expected.

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
