### ISSUE TITLE
ERROR: 2 matches found based on name: network rocketchat_default is ambiguous

### ISSUE THREAD

**Issue by skiiiks** [RocketChat/docs-old#1334]
I have followed step by step the manual at: https://github.com/RocketChat/docs/blob/master/installation/paas-deployments/aws/README.md

Problem 1)
I had tons of "Unsupported config option for services service: 'rocketchat'" in the logs.
I read is about the version of the docker-compose, so I changed from 1.4.2 to 1.6.0

Problem 2)
Now I have tons of this in the logs:
ERROR: 2 matches found based on name: network rocketchat_default is ambiguous

And I don't know how to fix it :-(

**Comment by sshniro** [comment]
I presume you are using Ubuntu 14 , can you switch to Ubuntu 16 and install docker.

Install docker-compose via: 
`sudo apt install docker-compose`
This will install docker-compose `version 1.8.0` or install 1.8.0 manually

Then create the docker-compose file and run this commands accordingly.
```
docker-compose up -d mongo
docker-compose up -d mongo-init-replica
docker-compose up -d rocketchat
```
I was running under these configurations and did not encounter such issues.

At the end you should see something similar in the Rocket.Chat logs
![image](https://user-images.githubusercontent.com/13045528/59209621-05d52000-8bac-11e9-97de-98b954aab734.png)

**Comment by skiiiks** [comment]
Well, I'm using what it's said in that manual ... I assumed it had to be that way ;-)
So I presume that manual is not updated properly , right ? ;-)

**Comment by sshniro** [comment]
Ok, I ran with your configurations, and for docker-compose version 1.4 the installation fails because of the docker-compose file version (v2). If you update docker-compose to 1.8.0 then it will work. And the current stable version provided in docker-compose is 1.24.0. The document needs to be updated. 
https://docs.docker.com/compose/install/

This is the official docker-compose image provided by Rocket.Chat. The following file is similar to the docker-compose file provided in the aws documentation. So updating the docker-compose version will do the fix.
https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml

**Comment by skiiiks** [comment]
I've tried with 1.8.0 and have the same problem :
ERROR: 2 matches found based on name: network rocketchat_default is ambiguous

Also with 1.24.0. and also the same problem (with the docker-compose.yml of the documentation, and with the one you posted). Same problem:
ERROR: 2 matches found based on name: network rocketchat_default is ambiguous

I think the problem is Ubuntu 14 ... I will change to Ubuntu 16

**Comment by Rodriq** [comment]
Guide for setup now here https://docs.rocket.chat/quick-start/deploying-rocket.chat/cloud-deployments/aws#install-docker-and-docker-compose
