### ISSUE TITLE
Mongo doesn't start after changed mongod.conf

### ISSUE THREAD

**Issue by ttsrg** [RocketChat/docs-old#1471]
Hello .
I've used this manual:
https://rocket.chat/docs/installation/manual-installation/debian/

After using next commands, mongo didn't start and showed error with  status=100:
sudo sed -i "s/^#  engine:/  engine: mmapv1/"  /etc/mongod.conf
sudo sed -i "s/^#replication:/replication:\n  replSetName: rs01/" /etc/mongod.conf

> 
> ** WARNING: Support for MMAPV1 storage engine has been deprecated and will be
>          removed in version 4.2. Please plan to migrate to the wiredTiger          storage engine.
> **          See http://dochub.mongodb.org/core/deprecated-mmapv1

Solution was change engine to  - wiredTiger

**Comment by Rodriq** [comment]
Starting with the major release `4.X.Y` of Rocket.Chat, MongoDB setup with WiredTiger storage engine is mandatory rather than the deprecated mmap.
Here you will find a guide on how to migrate to WiredTiger following the recommended deployment method. https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose/docker-containers/mongodb-mmap-to-wiredtiger-migration

Additional support on the MongoDB release https://www.mongodb.com/docs/manual/release-notes/4.0/#deprecate-mmapv1
