### ISSUE TITLE
Iframe embedded layout

### ISSUE THREAD

**Issue by juliensl** [RocketChat/docs-old#1671]
Hi everybody ! 

In the Iframe embedded layout, it is written : 
`Adittionaly, you can enable the top navbar in the embedded layout by going to “Administration -> Layout -> Interface -> Show top navbar in embedded layout”.`
developer-guides/embedded-layout/README.md

But, in my administration panel, I cannot see the button to enable the top navbar : 
![layout](https://user-images.githubusercontent.com/43228020/78268994-47eb9b80-7509-11ea-86ff-ccbc76dcd331.png)

Is the option disabled now ?

Thank you ! :) 

Rocket Chat version : 2.4.11

**Comment by Rodriq** [comment]
> Show top navbar

Did you manage to get around this?
I don't know about Version `2.4.11` but on the latest version, you'll find that at the `"Administration -> Layout -> User Interface -> Show top navbar in embedded layout”` right at the bottom.

**Comment by juliensl** [comment]
Hi @Rodriq , 

I'm using rocket chat with Snap, it's still at the 2.4.11 version, without the "Show top navbar in embedded layout" button :( 

I think that the latest/stable channel will move to the 3.x.x version soon, let's see after the update 👍

Thank you for your comment 😃

**Comment by dudanogueira** [comment]
Hi! This option is available on newer versions.

Consider using Docker instead of snap, as this is our suggested way of deployment:
https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods

Also, for support, please refer to our [Community Support Channel](https://open.rocket.chat/channel/support).

Thanks!
