### ISSUE TITLE
New users can't Register using api or  by admin  showing invalid Invalid email undefined [error-invalid-email] or Domain in Rocket.chat

### ISSUE THREAD

**Issue by janardna** [RocketChat/docs-old#1704]
Hi, I am using Rocket. chat 3.0.3 and latest One, when I go to create Users using not working email address(invalid email address )  before the version it is Registered but not Now, it is showing like Invalid Domain and by API " Invalid email undefined [error-invalid-email]" 
 
The DNS Domain Check Option by Default False.

anyone can help that would be great

**Comment by Rodriq** [comment]
Not quite sure why you are facing that. 
Check the following settings under **Administration** > **Accounts** > **Registration** and make sure it's correct
- Allowed Domains List
- Blocked Domains List

Otherwise, it might just be something else. The API endpoint is at https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/users-endpoints/create-user

Be sure to reopen this issue if you are still facing this issue
