### ISSUE TITLE
HowTo docker-containers confuses more than help.....

### ISSUE THREAD

**Issue by fl0wm0ti0n** [RocketChat/docs-old#1925]
https://github.com/RocketChat/docs/tree/master/installation/docker-containers

on point "6. Create the docker-compose.yml file & local directories" i coult only get the solution by googling around... ther eis no link or a hint what and how todo...

on point "8. Reboot and Status check" there is a missing screenshot.
[![docker ps -a](https://www.imageforge.us/images/c90bd55a7b357c20b18815a5560f43f3.png)](https://www.imageforge.us/image/60kNT)

and i think the whole HowDo should be renewed...

**Comment by fl0wm0ti0n** [comment]
update: also the part of the nginx doesnt work.. i checked it hundret times... https doesnt work... nginx doesnt log an error

**Comment by dudanogueira** [comment]
Hi!

Our docker documentation has changed since this Issue. please, check it out:
https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose

Also, we have a whole new SSL configuration section that has updated nginx info:
https://docs.rocket.chat/quick-start/environment-configuration/configuring-ssl-reverse-proxy

Let us know in our [Community Support Channel](https://open.rocket.chat/channel/support) if you face any errors with this

Thanks!
