### ISSUE TITLE
WhatsApp by Rocket.chat not appearing on the marketplace.

### ISSUE THREAD

**Issue by erickmff** [RocketChat/docs-old#1994]
The docs at this address was recently updated, but the whatsapp app mentioned doesn't appear on the marketplace.
https://github.com/RocketChat/docs/blob/master/guides/apps-guides/omnichannel-apps/whatsapp/whatsapp-installation.md

![image](https://user-images.githubusercontent.com/5818522/123794894-c1636c80-d8b9-11eb-99d1-0807412543f5.png)

PS: It was on marketplace before, installed on another instance and everything worked!

**Comment by ahabiba** [comment]
Same issue here !

**Comment by batzbenzer** [comment]
I have the same issue!
We chose rocket.chat because of the whatsapp integration (among other things). But after installing and setting it up I realized that the documentation/product presentation differs from reality. Are we doing something wrong or is this a known issue? Thanks for help rocket.chat-team!

**Comment by erickmff** [comment]
Has this problem been solved?

**Comment by murtaza98** [comment]
@erickmff Yeah this has been resolved, the app is now available on the marketplace 
![image](https://user-images.githubusercontent.com/34130764/145986545-a5234661-ea39-40a9-8b37-a5aafaa1f26b.png)

**Comment by Faria1212** [comment]
Yes. It's been resolved
