### ISSUE TITLE
Missing instructions about doing backup/restore

### ISSUE THREAD

**Issue by FibreFoX** [RocketChat/docs-old#630]
This is a followup of the discussion from this thread: https://github.com/RocketChat/Rocket.Chat/issues/2436#issuecomment-368349738

Currently there is no documented way of creating backups nor how to restore from a created backup. This needs to be added to the documentation. As #62 is only about DOCKER, this is about a generic way how to create backups.

**Comment by nodiscc** [comment]
Hi,
I can work on this.
As far as I know the only data that needs to be backed up is:
- a dump of the mongodb database
- the uploads directory _if_ you use something else than GridFS

Is that right?

**Comment by nodiscc** [comment]
@TwizzyDizzy ping (since you suggested opening this issue at https://github.com/RocketChat/Rocket.Chat/issues/2436#issuecomment-372031382)

I can start adding the relevant docs if my comment above is on point, and if I get some reassurance that my PR will be reviewed (I have a PR in https://github.com/RocketChat/Rocket.Chat that is lingering for months without any review). Is my description of the backup procedure correct?

**Comment by Rodriq** [comment]
- Docker Backup/Restore => https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/docker-and-docker-compose/docker-containers/docker-mongo-backup-and-restore
- Snaps Backup/Restore => https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/snaps/snap-backup-and-restore
- rocketchatctl => https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/rocketchatctl#backup-rocketchatctl
