### ISSUE TITLE
Can't change chat type.

### ISSUE THREAD

**Issue by 101st** [RocketChat/docs-old#920]
Example Call
```
curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq" \
     -H "X-User-Id: aobEdbYhXfu5hkeqG" \
     -H "Content-type: application/json" \
     http://localhost:3000/api/v1/channels.setType \
     -d '{ "roomId": "ByehQjC44FwMeiLbX", "type": "p" }'
```
If field "type" is "p" the operation succeeds
If field "type" is "с" the operation fails
```
{ success: false,
     error:
      'The required "roomId" or "roomName" param provided does
not match any channel [error-room-not-found]',
     errorType: 'error-room-not-found' } }
```
Both operations for the same chat.
Also i used admin authToken and userId.
I can't do anythings with private chat, cuz i didn't see them anymore. (op. like : channels.info ...)

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
